name: maud_accuracy_of_target_capitalization_rw_outstanding_shares_bringdown_standard_answer
reasoning_type: interpretation
legal_domain: public
language: en
answer_type: classification
labels:
- A
- B
- C
- D
metric: balanced_accuracy
description: 'Read an excerpt from a merger agreement and answer: how accurate must
  the capitalization representations and warranties be according to the bring down
  provision?'
version: 1
source: '[Atticus Project](https://www.atticusprojectai.org/maud)'
license: '[CC By 4.0](https://creativecommons.org/licenses/by/4.0/)'
imported_from: https://github.com/mustapha0101/LexiorBench/tree/main/tasks/maud_accuracy_of_target_capitalization_rw_(outstanding_shares)_bringdown_standard_answer
