name: maud_additional_matching_rights_period_for_modifications_cor
reasoning_type: interpretation
legal_domain: public
language: en
answer_type: classification
labels:
- A
- B
- C
- D
- E
metric: balanced_accuracy
description: 'Read an excerpt from a merger agreement and answer: how long is the
  additional matching rights period for modifications in case the board changes its
  recommendation?'
version: 1
source: '[Atticus Project](https://www.atticusprojectai.org/maud)'
license: '[CC By 4.0](https://creativecommons.org/licenses/by/4.0/)'
imported_from: https://github.com/mustapha0101/LexiorBench/tree/main/tasks/maud_additional_matching_rights_period_for_modifications_(cor)
