name: overruling
reasoning_type: rhetorical-understanding
legal_domain: public
language: en
answer_type: classification
labels:
- 'No'
- 'Yes'
metric: balanced_accuracy
description: Classify whether a sentence from a judicial opinion overrules a previous
  case.
version: 1
source: '[CaseHOLD](https://github.com/reglab/casehold)'
license: '[CC By 4.0](https://creativecommons.org/licenses/by/4.0/)'
imported_from: https://github.com/mustapha0101/LexiorBench/tree/main/tasks/overruling
