name: supply_chain_disclosure_best_practice_certification
reasoning_type: interpretation
legal_domain: public
language: en
answer_type: classification
labels:
- 'No'
- 'Yes'
metric: balanced_accuracy
description: Given a supply chain disclosure, determine if the statement discloses
  whether the retail seller or manufacturer requires direct suppliers to certify that
  they comply with labor and anti-trafficking laws.
version: 1
source: Adam Chilton & Galit Sarfaty
license: '[CC by 4.0](https://creativecommons.org/licenses/by/4.0/)'
imported_from: https://github.com/mustapha0101/LexiorBench/tree/main/tasks/supply_chain_disclosure_best_practice_certification
