name: supply_chain_disclosure_best_practice_training
reasoning_type: interpretation
legal_domain: public
language: fr
answer_type: classification
labels:
- Non
- Oui
metric: balanced_accuracy
description: Déterminer si la divulgation décrit des programmes de formation sur la
  détection du travail forcé, conformément à la Loi sur la lutte contre le travail
  forcé et le travail des enfants dans les chaînes d'approvisionnement (Canada, S-211,
  2023) (Oui/Non).
version: 2
target_jurisdiction: Federal CA
