name: cuad_rofr_rofo_rofn
reasoning_type: interpretation
legal_domain: public
language: en
answer_type: classification
labels:
- 'No'
- 'Yes'
metric: balanced_accuracy
description: Classify if the clause grant one party a right of first refusal, right
  of first offer or right of first negotiation to purchase, license, market, or distribute
  equity interest, technology, assets, products or services.
version: 1
source: '[Atticus Project](https://www.atticusprojectai.org/cuad>)'
license: '[CC By 4.0](https://creativecommons.org/licenses/by/4.0/)'
imported_from: https://github.com/mustapha0101/LexiorBench/tree/main/tasks/cuad_rofr-rofo-rofn
